using System.ComponentModel.DataAnnotations;

namespace Commander.Dtos
{
    public class CommandUpdateDto
    {
        // This one is autogenerated in the db. Hence not needed to give to the client
        //  public int Id { get; set; }

        [Required]
        [MaxLength(250)]
        public string HowTo { get; set; }   

        [Required]
        public string Line { get; set; }

        [Required]
        public string Platform { get; set; }
    }
}